#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "pl-PL"
title = "Ak47"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Wpisy"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "O Mnie"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Tagi"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 5



  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Bądźmy w kontakcie"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "Danto is a news and magazine Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Lifestylowo"
    hero__description = "Najnowsze technologie, wiara, fotografia oraz nowotworowe faq."


  #-------------------------------
  # Tags Section Settings
  [params.tags_section]
    enable = true
    number_posts = 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
    number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

  [[params.tag]]
    tag = "lifestyle"

  [[params.tag]]
    tag = "technologia"

  [[params.tag]]
    tag = "rak"

  [[params.tag]]
    tag = "fotografia"


  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = true
    section_title = "Meet our authors"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = "Zdobywaj wiedzę, inspirację i nadzieję z moim blogiem lifestyle - o nowotworach, nowoczesnych technologiach i fotografii!"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/T3Kornel"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Bądźmy w kontakcie"
    mailchimp__description = "Subskrybuj aby być na bieżąco z najnowszymy wpisami."
    mailchimp__identifier = "https://ak47.us14.list-manage.com/subscribe?u=9a2a24924bcf33e9e31d8d621&id=aec321bacd" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Twój adres email"
    mailchimp__button__text = "Subskrybuj"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "poczta@ak47.pl" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "www.ak47.pl" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false